assert_language_trees(
  "tests/fixtures/basic.sh",
  "bash",
  { "sql", "python", "lua", "javascript", "typescript", "ruby", "perl" }
)
assert_injected_node("tests/fixtures/basic.sh", "bash", "SELECT id, email", "keyword_select")
assert_injected_node("tests/fixtures/basic.sh", "bash", "SELECT id, email, status", "keyword_select")
assert_injected_node("tests/fixtures/basic.sh", "bash", "DELETE FROM users", "keyword_delete")
assert_injected_node("tests/fixtures/basic.sh", "bash", "SELECT id FROM logs", "keyword_select")
assert_injected_node("tests/fixtures/basic.sh", "bash", "SELECT id, email FROM users", "keyword_select")
assert_injected_node("tests/fixtures/basic.sh", "bash", "UPDATE users SET status", "keyword_update")
assert_injected_node("tests/fixtures/basic.sh", "bash", "SELECT count(*) FROM users", "keyword_select")
assert_injected_node("tests/fixtures/basic.sh", "bash", "INSERT INTO users", "keyword_insert")
assert_injected_node("tests/fixtures/basic.c", "c", "UPDATE users", "keyword_update")
assert_injected_node("tests/fixtures/basic.c", "c", "INSERT INTO users (email, status)", "keyword_insert")
assert_injected_node("tests/fixtures/basic.c", "c", "WITH recent_users AS (", "keyword_with")
assert_injected_node("tests/fixtures/basic.c", "c", "CREATE TABLE audit_logs (", "keyword_create")
assert_injected_node("tests/fixtures/basic.c", "c", "ORDER BY status", "keyword_order")
assert_injected_node("tests/fixtures/basic.c", "c", "ALTER TABLE audit_logs", "keyword_alter")
assert_injected_node("tests/fixtures/basic.c", "c", "GROUP BY user_id", "keyword_group")
assert_injected_node("tests/fixtures/basic.c", "c", "DELETE FROM audit_logs", "keyword_delete")
assert_injected_node("tests/fixtures/basic.c", "c", "CREATE INDEX", "keyword_create")
assert_injected_node("tests/fixtures/basic.c", "c", "row_number() OVER", "identifier")
assert_injected_node("tests/fixtures/basic.c", "c", "INSERT INTO audit_logs", "keyword_insert")
assert_injected_node("tests/fixtures/basic.c", "c", "CREATE TABLE projects", "keyword_create")
assert_injected_node("tests/fixtures/basic.c", "c", "SELECT email", "keyword_select")
assert_injected_node("tests/fixtures/basic.c", "c", "UPDATE projects", "keyword_update")
assert_injected_node("tests/fixtures/basic.c", "c", "INSERT INTO projects", "keyword_insert")
assert_injected_node("tests/fixtures/basic.c", "c", "DELETE FROM projects", "keyword_delete")
assert_injected_node("tests/fixtures/basic.c", "c", "WHERE name = 'core'", "keyword_where")
assert_injected_node("tests/fixtures/basic.c", "c", "WHERE id = $1", "keyword_where")
assert_injected_node("tests/fixtures/basic.c", "c", "WHERE name = $1", "keyword_where")
assert_injected_node("tests/fixtures/basic.c", "c", "ORDER BY name", "keyword_order")
assert_injected_node("tests/fixtures/basic.c", "c", "WHERE id > 0", "keyword_where")
assert_injected_node("tests/fixtures/basic.cpp", "cpp", "SELECT id, email", "keyword_select")
assert_injected_node("tests/fixtures/basic.cpp", "cpp", "UPDATE users", "keyword_update")
assert_injected_node("tests/fixtures/basic.cpp", "cpp", "INSERT INTO users (email, status)", "keyword_insert")
assert_injected_node("tests/fixtures/basic.cpp", "cpp", "WITH recent_users AS (", "keyword_with")
assert_injected_node("tests/fixtures/basic.cpp", "cpp", "CREATE TABLE audit_logs (", "keyword_create")
assert_injected_node("tests/fixtures/basic.cpp", "cpp", "ALTER TABLE audit_logs", "keyword_alter")
assert_injected_node("tests/fixtures/basic.cpp", "cpp", "GROUP BY user_id", "keyword_group")
assert_injected_node("tests/fixtures/basic.cpp", "cpp", "UPDATE audit_logs", "keyword_update")
assert_injected_node("tests/fixtures/basic.cpp", "cpp", "INSERT INTO audit_logs", "keyword_insert")
assert_injected_node("tests/fixtures/basic.cpp", "cpp", "DELETE FROM audit_logs", "keyword_delete")
assert_injected_node("tests/fixtures/basic.cpp", "cpp", "CREATE INDEX idx_audit_logs_message", "keyword_create")
assert_injected_node("tests/fixtures/basic.cpp", "cpp", "ORDER BY id", "keyword_order")
assert_injected_node("tests/fixtures/basic.cpp", "cpp", "ALTER TABLE audit_logs ADD COLUMN updated_at", "keyword_alter")
assert_injected_node("tests/fixtures/basic.cpp", "cpp", "WHERE email = $1", "keyword_where")
assert_injected_node("tests/fixtures/basic.cpp", "cpp", "WHERE message = $1", "keyword_where")
assert_injected_node("tests/fixtures/basic.cpp", "cpp", "WHERE message = 'created'", "keyword_where")
assert_injected_node("tests/fixtures/basic.cpp", "cpp", "CREATE TABLE events (", "keyword_create")
assert_injected_node("tests/fixtures/basic.cpp", "cpp", "WHERE name = ?", "keyword_where")
assert_injected_node("tests/fixtures/basic.cpp", "cpp", "SELECT count(*)", "keyword_select")
assert_injected_node("tests/fixtures/basic.cpp", "cpp", "FROM marked_users", "keyword_from")
assert_injected_node("tests/fixtures/basic.cpp", "cpp", "DELETE FROM marked_users", "keyword_delete")
assert_injected_node("tests/fixtures/basic.cpp", "cpp", "FROM qt_users", "keyword_from")
assert_injected_node("tests/fixtures/basic.cpp", "cpp", "FROM sqlite_users", "keyword_from")
assert_injected_node("tests/fixtures/basic.cpp", "cpp", "FROM free_query_users", "keyword_from")
assert_injected_node("tests/fixtures/basic.cpp", "cpp", "FROM soci_users", "keyword_from")
assert_injected_node("tests/fixtures/basic.cpp", "cpp", "FROM soci_prepared_users", "keyword_from")
assert_injected_node("tests/fixtures/basic.go", "go", "SELECT id, name", "keyword_select")
assert_injected_node("tests/fixtures/basic.cs", "c_sharp", "SELECT Id, Email", "keyword_select")
assert_injected_node("tests/fixtures/basic.cs", "c_sharp", "UPDATE Users", "keyword_update")
assert_injected_node("tests/fixtures/basic.cs", "c_sharp", "INSERT INTO Users (Email, Status)", "keyword_insert")
assert_injected_node("tests/fixtures/basic.cs", "c_sharp", "WITH recent_users AS (", "keyword_with")
assert_injected_node("tests/fixtures/basic.cs", "c_sharp", "CREATE TABLE AuditLogs (", "keyword_create")
assert_injected_node("tests/fixtures/basic.cs", "c_sharp", "GROUP BY Status", "keyword_group")
assert_injected_node("tests/fixtures/basic.cs", "c_sharp", "DELETE FROM Users", "keyword_delete")
assert_injected_node("tests/fixtures/basic.cs", "c_sharp", "ALTER TABLE AuditLogs", "keyword_alter")
assert_injected_node("tests/fixtures/basic.java", "java", "SELECT id, email", "keyword_select")
assert_injected_node("tests/fixtures/basic.java", "java", "UPDATE users", "keyword_update")
assert_injected_node("tests/fixtures/basic.java", "java", "INSERT INTO users (email, status)", "keyword_insert")
assert_injected_node("tests/fixtures/basic.java", "java", "WITH recent_users AS (", "keyword_with")
assert_injected_node("tests/fixtures/basic.java", "java", "CREATE TABLE audit_logs (", "keyword_create")
assert_injected_node("tests/fixtures/basic.java", "java", "GROUP BY status", "keyword_group")
assert_injected_node("tests/fixtures/basic.java", "java", "DELETE FROM users", "keyword_delete")
assert_injected_node("tests/fixtures/basic.java", "java", "ALTER TABLE audit_logs", "keyword_alter")
assert_injected_node("tests/fixtures/basic.java", "java", "FROM comment_marked_users", "keyword_from")
assert_injected_node("tests/fixtures/basic.java", "java", "DELETE FROM comment_marked_users", "keyword_delete")
assert_injected_node("tests/fixtures/basic.java", "java", "FROM annotated_users", "keyword_from")
assert_injected_node("tests/fixtures/basic.java", "java", "SELECT active_id", "keyword_select")
assert_injected_node("tests/fixtures/basic.java", "java", "INSERT INTO annotated_users", "keyword_insert")
assert_injected_node("tests/fixtures/basic.java", "java", "UPDATE annotated_users", "keyword_update")
assert_injected_node("tests/fixtures/basic.java", "java", "DELETE FROM annotated_users", "keyword_delete")
assert_injected_node("tests/fixtures/basic.java", "java", "FROM spring_users", "keyword_from")
assert_injected_node("tests/fixtures/basic.java", "java", "FROM spring_reversed_users", "keyword_from")
assert_injected_node("tests/fixtures/basic.java", "java", "FROM hibernate_subselect_users", "keyword_from")
assert_injected_node("tests/fixtures/basic.java", "java", "INSERT INTO hibernate_users", "keyword_insert")
assert_injected_node("tests/fixtures/basic.java", "java", "DELETE FROM hibernate_users", "keyword_delete")
assert_injected_node("tests/fixtures/basic.java", "java", "FROM jpa_native_users", "keyword_from")
assert_injected_node("tests/fixtures/basic.java", "java", "FROM User u", "keyword_from")
assert_injected_node("tests/fixtures/basic.java", "java", "FROM jdbc_template_users", "keyword_from")
assert_injected_node("tests/fixtures/basic.java", "java", "UPDATE jdbc_template_users", "keyword_update")
assert_injected_node("tests/fixtures/basic.java", "java", "FROM jdbi_users", "keyword_from")
assert_injected_node("tests/fixtures/basic.java", "java", "UPDATE jdbi_users", "keyword_update")
assert_injected_node("tests/fixtures/basic.java", "java", "FROM jooq_users", "keyword_from")
assert_injected_node("tests/fixtures/basic.java", "java", "FROM jooq_result_users", "keyword_from")
assert_injected_node("tests/fixtures/basic.js", "javascript", "SELECT id, email", "keyword_select")
assert_injected_node("tests/fixtures/basic.js", "javascript", "GROUP BY status", "keyword_group")
assert_injected_node("tests/fixtures/basic.js", "javascript", "UPDATE users", "keyword_update")
assert_injected_node("tests/fixtures/basic.js", "javascript", "ON CONFLICT (email)", "keyword_on")
assert_injected_node("tests/fixtures/basic.js", "javascript", "DELETE FROM users", "keyword_delete")
assert_injected_node("tests/fixtures/basic.kt", "kotlin", "SELECT id, email", "keyword_select")
assert_injected_node("tests/fixtures/basic.kt", "kotlin", "UPDATE users", "keyword_update")
assert_injected_node("tests/fixtures/basic.kt", "kotlin", "INSERT INTO users (email, status)", "keyword_insert")
assert_injected_node("tests/fixtures/basic.kt", "kotlin", "CREATE TABLE audit_logs (", "keyword_create")
assert_injected_node("tests/fixtures/basic.kt", "kotlin", "WITH recent_users AS (", "keyword_with")
assert_injected_node("tests/fixtures/basic.kt", "kotlin", "GROUP BY status", "keyword_group")
assert_injected_node("tests/fixtures/basic.kt", "kotlin", "DELETE FROM users", "keyword_delete")
assert_injected_node("tests/fixtures/basic.kt", "kotlin", "ALTER TABLE users", "keyword_alter")
assert_injected_node("tests/fixtures/basic.kt", "kotlin", "FROM kotlin_annotated_users", "keyword_from")
assert_injected_node("tests/fixtures/basic.kt", "kotlin", "SELECT active_id", "keyword_select")
assert_injected_node("tests/fixtures/basic.kt", "kotlin", "INSERT INTO kotlin_annotated_users", "keyword_insert")
assert_injected_node("tests/fixtures/basic.kt", "kotlin", "UPDATE kotlin_annotated_users", "keyword_update")
assert_injected_node("tests/fixtures/basic.kt", "kotlin", "DELETE FROM kotlin_annotated_users", "keyword_delete")
assert_injected_node("tests/fixtures/basic.kt", "kotlin", "FROM kotlin_spring_users", "keyword_from")
assert_injected_node("tests/fixtures/basic.kt", "kotlin", "FROM kotlin_spring_reversed_users", "keyword_from")
assert_injected_node("tests/fixtures/basic.ex", "elixir", "SELECT id, email", "keyword_select")
assert_injected_node("tests/fixtures/basic.ex", "elixir", "SELECT status, count(*) AS total", "keyword_select")
assert_injected_node("tests/fixtures/basic.ex", "elixir", "SELECT id FROM users", "keyword_select")
assert_injected_node("tests/fixtures/basic.ex", "elixir", "UPDATE users SET status", "keyword_update")
assert_injected_node("tests/fixtures/basic.ex", "elixir", "INSERT INTO users", "keyword_insert")
assert_injected_node("tests/fixtures/basic.ex", "elixir", "DELETE FROM users", "keyword_delete")
assert_injected_node("tests/fixtures/basic.ex", "elixir", "CREATE TABLE audit_logs", "keyword_create")
assert_injected_node("tests/fixtures/basic.ex", "elixir", "ALTER TABLE users", "keyword_alter")
assert_injected_node("tests/fixtures/basic.ex", "elixir", "SELECT id FROM logs", "keyword_select")
assert_injected_node("tests/fixtures/basic.lua", "lua", "SELECT id, email", "keyword_select")
assert_injected_node("tests/fixtures/basic.lua", "lua", "CREATE TABLE users (", "keyword_create")
assert_injected_node("tests/fixtures/basic.lua", "lua", "WITH recent_users AS (", "keyword_with")
assert_injected_node("tests/fixtures/basic.lua", "lua", "INSERT INTO users (email, status)", "keyword_insert")
assert_injected_node("tests/fixtures/basic.lua", "lua", "UPDATE users SET status = '%s'", "keyword_update")
assert_injected_node("tests/fixtures/basic.php", "php", "SELECT id, email", "keyword_select")
assert_injected_node("tests/fixtures/basic.php", "php", "UPDATE users", "keyword_update")
assert_injected_node("tests/fixtures/basic.php", "php", "INSERT INTO users (email, status)", "keyword_insert")
assert_injected_node("tests/fixtures/basic.php", "php", "WITH recent_users AS (", "keyword_with")
assert_injected_node("tests/fixtures/basic.php", "php", "CREATE TABLE audit_logs (", "keyword_create")
assert_injected_node("tests/fixtures/basic.php", "php", "GROUP BY status", "keyword_group")
assert_injected_node("tests/fixtures/basic.php", "php", "DELETE FROM users", "keyword_delete")
assert_injected_node("tests/fixtures/basic.php", "php", "ALTER TABLE audit_logs", "keyword_alter")
assert_injected_node("tests/fixtures/basic.pl", "perl", "SELECT id, email FROM perl_users", "keyword_select")
assert_injected_node("tests/fixtures/basic.pl", "perl", "SELECT id, email, status", "keyword_select")
assert_injected_node("tests/fixtures/basic.pl", "perl", "UPDATE perl_users SET status", "keyword_update")
assert_injected_node("tests/fixtures/basic.pl", "perl", "INSERT INTO perl_users", "keyword_insert")
assert_injected_node("tests/fixtures/basic.pl", "perl", "DELETE FROM perl_users", "keyword_delete")
assert_injected_node("tests/fixtures/basic.pl", "perl", "SELECT * FROM perl_users", "keyword_select")
assert_injected_node("tests/fixtures/basic.pl", "perl", "SELECT id, email FROM perl_users WHERE id", "keyword_select")
assert_injected_node("tests/fixtures/basic.pl", "perl", "CREATE TABLE perl_audit_logs", "keyword_create")
assert_injected_node("tests/fixtures/basic.pl", "perl", "ALTER TABLE perl_users", "keyword_alter")
assert_injected_node("tests/fixtures/basic.py", "python", "CREATE TABLE users (", "keyword_create")
assert_injected_node("tests/fixtures/basic.py", "python", "DELETE FROM users", "keyword_delete")
assert_injected_node(
  "tests/fixtures/basic.rb",
  "ruby",
  "SELECT id, email FROM users WHERE active = true",
  "keyword_select"
)
assert_injected_node("tests/fixtures/basic.rb", "ruby", "CREATE TABLE users (", "keyword_create")
assert_injected_node("tests/fixtures/basic.rb", "ruby", "GROUP BY status", "keyword_group")
assert_injected_node("tests/fixtures/basic.rb", "ruby", "UPDATE users", "keyword_update")
assert_injected_node("tests/fixtures/basic.rb", "ruby", "INSERT INTO users (email, status)", "keyword_insert")
assert_injected_node("tests/fixtures/basic.rb", "ruby", "WITH recent_users AS (", "keyword_with")
assert_injected_node("tests/fixtures/basic.rb", "ruby", "ALTER TABLE users", "keyword_alter")
assert_injected_node("tests/fixtures/basic.rs", "rust", "CREATE TABLE users (", "keyword_create")
assert_injected_node("tests/fixtures/basic.rs", "rust", "INSERT INTO users (email)", "keyword_insert")
assert_injected_node("tests/fixtures/basic.rs", "rust", "FROM sqlx_query_as_users", "keyword_from")
assert_injected_node("tests/fixtures/basic.rs", "rust", "FROM sqlx_scalar_users", "keyword_from")
assert_injected_node("tests/fixtures/basic.rs", "rust", "FROM diesel_users", "keyword_from")
assert_injected_node("tests/fixtures/basic.rs", "rust", "FROM sea_orm_users", "keyword_from")
assert_injected_node("tests/fixtures/basic.rs", "rust", "UPDATE sea_orm_users", "keyword_update")
assert_injected_node("tests/fixtures/basic.rs", "rust", "FROM manager_users", "keyword_from")
assert_injected_node("tests/fixtures/basic.rs", "rust", "DELETE FROM manager_users", "keyword_delete")
assert_injected_node(
  "tests/fixtures/basic.scala",
  "scala",
  "SELECT id, email FROM users WHERE active = true",
  "keyword_select"
)
assert_injected_node("tests/fixtures/basic.scala", "scala", "CREATE TABLE users (", "keyword_create")
assert_injected_node("tests/fixtures/basic.scala", "scala", "GROUP BY status", "keyword_group")
assert_injected_node("tests/fixtures/basic.scala", "scala", "UPDATE users", "keyword_update")
assert_injected_node("tests/fixtures/basic.scala", "scala", "INSERT INTO users (email, status)", "keyword_insert")
assert_injected_node("tests/fixtures/basic.scala", "scala", "WITH recent_users AS (", "keyword_with")
assert_injected_node("tests/fixtures/basic.scala", "scala", "ALTER TABLE users", "keyword_alter")
assert_injected_node("tests/fixtures/basic.ts", "typescript", "UPDATE users", "keyword_update")
assert_injected_node(
  "tests/fixtures/basic.ts",
  "typescript",
  "CREATE TABLE IF NOT EXISTS audit_logs (",
  "keyword_create"
)
assert_injected_node("tests/fixtures/basic.ts", "typescript", "WITH recent_users AS (", "keyword_with")
assert_injected_node("tests/fixtures/basic.xml", "xml", "FROM xml_users", "keyword_from")
assert_injected_node("tests/fixtures/basic.xml", "xml", "INSERT INTO xml_users", "keyword_insert")
assert_injected_node("tests/fixtures/basic.xml", "xml", "UPDATE xml_users", "keyword_update")
assert_injected_node("tests/fixtures/basic.xml", "xml", "DELETE FROM xml_users", "keyword_delete")
assert_injected_node("tests/fixtures/basic.xml", "xml", "FROM dynamic_xml_users", "keyword_from")
assert_injected_node("tests/fixtures/basic.xml", "xml", "UPDATE dynamic_xml_users", "keyword_update")
assert_injected_node("tests/fixtures/basic.xml", "xml", "FROM conditional_xml_users", "keyword_from")
assert_injected_node("tests/fixtures/basic.zig", "zig", "SELECT id, email", "keyword_select")
assert_injected_node("tests/fixtures/basic.zig", "zig", "CREATE TABLE audit_logs (", "keyword_create")
assert_injected_node("tests/fixtures/basic.zig", "zig", "WITH recent_users AS (", "keyword_with")
assert_injected_node("tests/fixtures/basic.zig", "zig", "UPDATE users", "keyword_update")
assert_injected_node("tests/fixtures/basic.zig", "zig", "INSERT INTO users (email)", "keyword_insert")

print("smoke test passed")

